# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-01 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Name')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Date modified')),
            ],
        ),
    ]
